### ISSUE TITLE
Allow Builds to specify node selectors and affinity

### ISSUE THREAD

**Issue by ImJasonH** [knative/build#116]
Allowing a `Build` to specify `nodeSelector`s would allow users to constrain the nodes that can be used to run builds. Specifying `affinity` would allow builds to give hints/suggestions to the scheduler, to [specify node affinity and pod affinity/anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/).

This would give users the ability to specify that a build should(n't) happen in a specific zone or region, should happen on a node running a specific OS or architecture, should happen on a node with another build (which could enable better cross-build caching), etc.

If a `Build` specifies node selectors or affinity, these would be simply passed directly to the `Pod` that runs the build on the cluster.

```
spec:
  steps:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    args: ["version"]
  nodeSelector:
    disktype: ssd
```

This would make sure to assign the build to a node with SSD.

Likewise for affinity:

```
spec:
  steps:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    args: ["version"]
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/e2e-az-name
            operator: In
            values:
            - e2e-az1
            - e2e-az2
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
```

This rather complex and verbose configuration requires that the build be scheduled into one of the two listed availability zones, and prefers (but does not require) that the build be scheduled on a node with the given label key/value.
