### ISSUE TITLE
Build controller should validate build templates upon admission

### ISSUE THREAD

**Issue by bsnchan** [knative/build#131]
/area API
/kind bug

## Expected Behavior

If I have a BuildTemplate with the an environment variable of true that is unquoted (i.e. the environment variable `SOME_ENV_VAR` is a bool instead of a string): 

```
apiVersion: build.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: buildpack
spec:
 ...
  steps:
  - name: export
    image: packs/cf:export
    workingdir: /in
    args: ["${IMAGE}"]
    env:
    - name: SOME_ENV_VAR
      value: true
```

The build controller should validate this BuildTemplate to return an error stating that the build template is incorrect.

## Actual Behavior

The controller accepts this build template and does not perform any validation on it. The user won't see any errors until attempting to use this build template.
