### ISSUE TITLE
No sample shows me how to build a non trivial Go application

### ISSUE THREAD

**Issue by dgageot** [knative/build#162]
/kind doc

## Expected Behavior

As a developer who's going to use Build CRD to build a Go application, I'd like to have a sample that shows me how to write the `build.yaml`. Go application tend to be touchy about being cloned under `GOPATH`.

## Actual Behavior

I couldn't find any. Nor could I guess how to do that from existing documentation.
I mean I did but it's more bash-fu that a proper build descriptor.

```yaml
apiVersion: build.dev/v1alpha1
kind: Build
metadata:
  name: git-build
spec:
  source:
    git:
      url: https://github.com/GoogleContainerTools/skaffold.git
      branch: master
  steps:
  - image: golang:1.10.2
    args: ["sh", "-c", "mkdir -p /go/src/github.com/GoogleContainerTools && ln -s /workspace /go/src/github.com/GoogleContainerTools/skaffold && make"]
  - image: busybox
    args: ["./out/skaffold", "version"]
```
