### ISSUE TITLE
Multiple cred annotations of the same type in a single cert don't work

### ISSUE THREAD

**Issue by evankanderson** [knative/build#188]
## Expected Behavior

As described in https://github.com/knative/build/blob/master/docs/auth.md#guiding-credential-selection, it should be possible to use multiple `knative.dev/docker-N` annotations on a single secret to use the same secret for multiple repos:

```yaml
apiVersion: v1
kind: Secret
metadata:
  annotations:
    build.dev/git-0: https://github.com
    build.dev/git-1: https://gitlab.com
    build.dev/docker-0: https://gcr.io
type: kubernetes.io/basic-auth
data:
  username: <base64 encoded>
  password: <base64 encoded>
```

## Actual Behavior

One of the credentials is chosen, possibly at random. (I had the order "gcr.io", "us.gcr.io", "eu.gcr.io", "asia.gcr.io" and got "gcr.io". Swapping the order of the first two got me "eu.gcr.io".)

## Steps to Reproduce the Problem

1. Create a GCP service account with storage admin access, called "push-images@$PROJECTID.iam.serviceaccount.com". I used the web UI for this.
1. Download the keys for the service account with:
   ```shell
   gcloud iam service-accounts keys create push-key --iam-account push-images@$PROJECTID.iam.gserviceaccount.com
   ```
1. Create a secret and service account base file:
   ```yaml
   apiVersion: v1
   kind: ServiceAccount
   metadata:
     name: builder
   secrets:
   - name: gcr-creds
   ---
   apiVersion: v1
   kind: Secret
   metadata:
     name: gcr-creds
     annotations:
       build.dev/docker-0: https://us.gcr.io
       build.dev/docker-1: https://gcr.io
       build.dev/docker-2: https://eu.gcr.io
       build.dev/docker-3: https://asia.gcr.io
   type: kubernetes.io/basic-auth
   data:
     username: X2pzb25fa2V5  # _json_key, base64 encoded
     password:
   ```
1. Append the base64-encoded push-key from step 2:
   ```shell
   cat push-key | base64 -w 0 >> secrets.yaml
   ```
1. `kubectl apply -f secrets.yaml` to create the secrets
1. Reference the `builder` serviceAccountName in your build.
1. Start a build, and look at the args to the creds initializer, Only one domain is listed.
