### ISSUE TITLE
generated wrong docker config.json 

### ISSUE THREAD

**Issue by rootfs** [knative/build#195]
/kind bug

/assign @mattmoor 
## Expected Behavior
generated docker credentials should be correct and docker push should work

## Actual Behavior

docker push failed with wrong credential format
using the following secret
```
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.dev/docker-0: index.docker.io
type: kubernetes.io/basic-auth
data:
  username: 
  password: 
```
expected (after `docker login docker.io`)
```json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "xxxxxx"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/17.12.0-ce (linux)"
        }
}
```

generated format:
```json
{"auths":{"index.docker.io":{"username":"xxxx","password":"xxxxxx","auth":"xxxxxxx","
email":"not@val.id"}}}
```

most likely, `index.docker.io` should be `https://index.docker.io/v1/`  
## Steps to Reproduce the Problem

  1.
  2.
  3.

**Comment by alexellis** [comment]
I'm following the example in https://www.knative.dev/docs/build/auth/#guiding-credential-selection and got pointed here by @ImJasonH 

I ran `docker login` and then the following:

```
kubectl create secret generic regcred     --from-file=.dockerconfigjson=$HOME/.docker/config.json     --type=kubernetes.io/dockerconfigjson
```

I then assigned the secret to a serviceAccount and the serviceAccountName to the build but still get a 401.

The registry is the Docker Hub.

```
default/hello-build-pod-d03a04[build-step-build-push]: error pushing image: failed to push to destination index.docker.io/alexellis2/openfaas-cloud-test:0.1.0: unsupported status code 401; body: 
```

**Comment by alexellis** [comment]
I've also tried the following with the same 401 error:

```
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    build.knative.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
data: #Base64 encoded
  username: val
  password: val
```
