### ISSUE TITLE
Support ${COMMIT_SHA} (et al)

### ISSUE THREAD

**Issue by mattmoor** [knative/build#24]
In GCB, `$GIT_COMMIT` is a fairly widely used substitution, e.g. it can be used to give Docker images unique tags (with a hint of provenance).

I'd posit that this class of substitution is most useful in the context of a trigger (specifically a Git trigger), which is something we haven't meaningfully discussed and may want to keep out of scope for now.  I'm illustrating it here more to show my thinking than anything else:

```
apiVersion: cloudbuild.dev/v1alpha1
kind: GithubTrigger
spec:
  repo: # overload of GitSourceSpec
    url: https://github.com/foo/bar
    branch: <regexp, e.g. master>
    tag: <regexp, e.g. v[0-9.]+>
    refs: <regexp, e.g. refs/pulls/.*>

  # TODO(mattmoor): Additional conditions, e.g. PR from admin, comment from admin on PR.

  template:
    name: dockerfile-build-push
    namespace: cloud-builders
    arguments:
    - name: IMAGE
       value: gcr.io/foo/bar:${GIT_COMMIT}
```

/cc @ImJasonH
