### ISSUE TITLE
Bubble up Pod failures in Build

### ISSUE THREAD

**Issue by shashwathi** [knative/build#252]
## Expected Behavior
Pod `Pending`, `Unknown` phases should also be bubbled to the build controller

## Actual Behavior
Only pod `Failure` status is bubbled up in Build controller. 

## Steps to Reproduce the Problem

  1. Deploy 
```
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: failed-build
  labels:
    expect: failed
spec:
  steps:
  - name: write
    image: ubuntu:latest
    command: ["/bin/bash"]
    args: ["-c", "echo stuff > /workspace/stuff"]
  nodeSelector:
    disktype: fakessd
```
[Above example assumes there is no node with `fakessd` label ]
 2. `kubectl describe build failed-build` does not have any status update the issue

/area API
/kind bug
/kind dev

/assign @shashwathi

## Additional Info
1. Update build status msg/reason for `PENDING` and `Unknown` [pod phases](https://github.com/knative/build/blob/master/pkg/builder/cluster/builder.go#L94).
