### ISSUE TITLE
build pod should have namespaced labels

### ISSUE THREAD

**Issue by cppforlife** [knative/build#295]
/area API

/kind bug

## Expected Behavior

Build container should have a label that is namespaced with `build.knative.dev`

## Actual Behavior

Currently label is just build-name

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  creationTimestamp: "2018-08-02T20:57:31Z"
  generateName: foo-app-00001-
  labels:
    build-name: foo-app-00001 #<-----------------
  name: foo-app-00001-rk9zm
  namespace: default
```

Serving seems to have already namespaced their labels: https://github.com/knative/serving/blob/5b8542fb58044834d50f71a40d36b936e372a9ec/pkg/apis/serving/register.go

## Steps to Reproduce the Problem

  1. create a build that fails
  2. see yaml for the build pod
