### ISSUE TITLE
Build sets completionTime while in progress

### ISSUE THREAD

**Issue by mattmoor** [knative/build#383]
I see:
```
 status:
    builder: Cluster
    cluster:
      namespace: default
      podName: app-from-source-00001-kxj8j
    completionTime: 2018-09-29T20:58:43Z
    conditions:
    - lastTransitionTime: 2018-09-29T20:58:43Z
      message: Pending
      reason: 'pod status "Initialized":"False"; message: "containers with incomplete
        status: [build-step-build-and-push]"'
      status: Unknown
      type: Succeeded
```
