### ISSUE TITLE
Allow Build type to have multiple source inputs.

### ISSUE THREAD

**Issue by pivotal-nader-ziada** [knative/build#392]
## Expected Behavior
The Build CRD only accepts one input source to the build, but it could be required to have multiple github repos as sources, for example one for the application to build and another to run the tests

for example:
```
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: test-git-revision
  labels:
    expect: succeeded
spec:
  source:
    - git:
        url: https://github.com/bazelbuild/rules_docker
        revision: pull/100/head
    - git:
        url: https://github.com/bazelbuild/rules_docker
        revision: master
  template:
    name: dump-workspace-template
```

## Actual Behavior
Only one source is supported in the CRD

## Steps to Reproduce the Problem

  1. check the build types

## Additional Info
 * This is helpful for the implementation of the build pipeline resources
