### ISSUE TITLE
Build timeout `0` should be treated as unlimited

### ISSUE THREAD

**Issue by scothis** [knative/build#408]
## Expected Behavior

When setting the BuildSpec.Timeout to zero, the build should not treat that as a literal value, but instead disable the build timeout.

## Actual Behavior

The build times out immediately, making the build impossible to complete

```
    conditions:
    - lastTransitionTime: 2018-10-08T17:27:15Z
      message: Build "upper-00001" failed to finish within "0s"
      reason: BuildTimeout
      status: "False"
      type: Succeeded
```
## Steps to Reproduce the Problem

  1. apply build https://storage.googleapis.com/knative-releases/build/previous/v20181008-9825433/release.yaml
  2. apply serving https://storage.googleapis.com/knative-releases/serving/previous/v20181008-d8283a8/serving.yaml
  3. create a service with a build, without setting a build timeout

## Additional Info

The root cause of this issue is two fold:
1. build treats a timeout value of zero as literally zero
2. serving vendors a previous version of build which has BuildSpec.Timeout as type `Duration` and not the current type of `*Duration`. This causes new services without an explicit timeout to default to `0` which will always timeout.
