### ISSUE TITLE
Knative build creates duplicate pods

### ISSUE THREAD

**Issue by meteatamel** [knative/build#542]
Knative build consistently creates duplicate builds. This is my build definition:

```yaml
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: build-helloworld-csharp-gcr
spec:
  source:
    git:
      url: "https://github.com/knative/docs.git"
      revision: "v0.1.x"
    subPath: "serving/samples/helloworld-csharp/"
  steps:
  - name: build-and-push
    image: "gcr.io/kaniko-project/executor:v0.6.0"
    args:
    - "--dockerfile=/workspace/Dockerfile"
    - "--destination=gcr.io/MY_GCP_PROJECT/helloworld-csharp:v1"`
```

```bash
> kubectl get build
No resources found.
> kubectl apply -f build-helloworld-csharp-gcr.yaml 
build.build.knative.dev "build-helloworld-csharp-gcr" created
> kubectl get build
NAME                          AGE
build-helloworld-csharp-gcr   5s
> kubectl get pods
NAME                                              READY     STATUS     RESTARTS   AGE
build-helloworld-csharp-gcr-pod-e7d4b1            0/1       Init:2/3   0          8s
build-helloworld-csharp-gcr-pod-ea29fd            0/1       Init:1/3   0          7s
```
The first one gets stuck in this step:
```bash
INFO[0083] Taking snapshot of full filesystem...
```

The second one builds and pushes to GCR.

**Comment by sebgoa** [comment]
@ImJasonH we seem to face this issue as well in 0.3.0

**Comment by utka** [comment]
I see the same bug for my project

**Comment by ImJasonH** [comment]
I'm able to reproduce this, in about 2/11 tries:

```
$ while true; do kubectl apply -f build.yaml; sleep 10; kubectl get build build -ojsonpath="{.status.cluster.podName}"; echo; kubectl get pods; kubectl delete builds --all; done
build.build.knative.dev/build created
build-pod-3d7578
NAME               READY   STATUS     RESTARTS   AGE
build-pod-3d7578   0/1     Init:2/3   0          13s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-0633e0
NAME               READY   STATUS     RESTARTS   AGE
build-pod-0633e0   0/1     Init:2/3   0          12s
build-pod-58bfde   0/1     Init:2/3   0          13s  # <---- BOOM
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-41cf51
NAME               READY   STATUS        RESTARTS   AGE
build-pod-41cf51   0/1     Init:2/3      0          13s
build-pod-58bfde   0/1     Terminating   0          32s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-74c7fc
NAME               READY   STATUS     RESTARTS   AGE
build-pod-74c7fc   0/1     Init:2/3   0          14s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-257e44
NAME               READY   STATUS     RESTARTS   AGE
build-pod-257e44   0/1     Init:2/3   0          13s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-d8f2c8
NAME               READY   STATUS     RESTARTS   AGE
build-pod-d8f2c8   0/1     Init:2/3   0          14s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-a29228
NAME               READY   STATUS     RESTARTS   AGE
build-pod-a29228   0/1     Init:2/3   0          14s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-9e7202
NAME               READY   STATUS     RESTARTS   AGE
build-pod-9e7202   0/1     Init:2/3   0          14s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-6f54c4
NAME               READY   STATUS     RESTARTS   AGE
build-pod-6f54c4   0/1     Init:2/3   0          14s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-b9e009
NAME               READY   STATUS     RESTARTS   AGE
build-pod-b9e009   0/1     Init:2/3   0          14s
build.build.knative.dev "build" deleted
build.build.knative.dev/build created
build-pod-705e03
NAME               READY   STATUS        RESTARTS   AGE
build-pod-705e03   0/1     Init:2/3      0          12s
build-pod-af2f4a   0/1     Init:2/3      0          13s  # <---- BOOM
build-pod-b9e009   0/1     Terminating   0          34s
build.build.knative.dev "build" deleted
^C
```

Are others seeing this more reliably than this? My test is using `v0.3.0` against a cluster running `1.11.6-gke.3`.

**Comment by utka** [comment]
I tried around 5 times, it was doing that every time

**Comment by sebgoa** [comment]
About the same ~20% with:

```
apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: ls
spec:
  steps:
  - name: ls
    image: busybox
    args: ['ls']
```
