### ISSUE TITLE
Error: unknown flag when using --build-arg in buildtemplate

### ISSUE THREAD

**Issue by guyos** [knative/build#565]
/kind bug

## Expected Behavior
Build argument is passed to Dockerfile and arg value is used in the build
## Actual Behavior
Getting the following error when building...
```
Error: unknown flag: --build-arg A_TARGET
Usage:
  executor [flags]

Flags:
      --build-arg multi-arg type                  This flag allows you to pass in ARG values at build time. Set it repeatedly for multiple values.
...
```
## Steps to Reproduce the Problem

1. Create a buildtemplate that has a similar step to this where A_TARGET is an ARG in a Dockerfile
```
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
    - --build-arg A_TARGET=green
```
2. apply the build template
3. apply a build setting the variables
