### ISSUE TITLE
git source should have an optional "src_dir" setting

### ISSUE THREAD

**Issue by squee1945** [knative/build#91]
When specifying a `git` `source`, e.g., 

```
  source:
    git:
      url: https://github.com/mchmarny/rester-tester.git
      branch: master
```

It seems that we will need to allow the user to (optionally) identify the root of the source to be built, e.g., 

```
  source:
    git:
      url: https://github.com/mchmarny/rester-tester.git
      branch: master
      src_dir: webapp/src
```

A git repo may contain any number of supporting folders and the required build key file (e.g., `pom.xml`, `package.json`, `build.gradle`) may not be housed at the very top level.

When fetching the contents of this repo, only the `src_dir` contents should be placed in the build workspace. (Perhaps there is some git optimization that allows only this sub-folder to be fetched in the first place.)
